In [1]:
from Domains.Simulator20q import Simulator20q
from Experiments.online_fqi import run
import numpy as np
from Representations.ApproxRep import ApproxRep
from Representations import Representation

loading model
construct meta info for corpus
[u'birthplace', u'spouse', u'gender', u'profession', u'birthday', u'deathplace', u'nationality', u'education', u'Types']
Done initializing


In [2]:
s = Simulator20q()

In [6]:
s1 = s.step(s.s0(), 0)
s2 = s.step(s1[1], 1)
s3 = s.step(s2[1], 9)
s4 = s.step(s3[1], 3)
s5 = s.step(s4[1], 4)
s6 = s.step(s5[1], 5)
s7 = s.step(s6[1], 6)
s8 = s.step(s7[1], 7)
s9 = s.step(s8[1], 8)
s10 = s.step(s9[1], 9)
print s.person_inmind
print s1
print s2
print s3
print s4
print s5
print s6
print s7
print s8
print s9
print s10

{u'birthplace': [u'Ankara'], u'education': [u'Conservatoire de Paris'], u'name': u'"\u0130dil Biret"@en', u'degree': [], u'gender': [u'Female'], u'profession': [u'Pianist'], u'birthday': [u'941-11-21'], u'deathplace': [], u'nationality': [u'Turkey'], u'spouse': [], u'Types': [u'music.group_member', u'people.person', u'music.artist', u'award.award_winner']}
(-1.0, array([[ 16.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.]]), False)
(-1.0, array([[ 16.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   2.,   0.]]), False)
(10.0, array([[ 16.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   3.,   1.]]), True)
(-10.0, array([[ 16.,   1.,   0.,  15.,   0.,   0.,   0.,   0.,   0.,   4.,   1.]]), True)
(-10.0, array([[ 16.,   1.,   0.,  15.,  56.,   0.,   0.,   0.,   0.,   5.,   1.]]), True)
(-10.0, array([[ 16.,   1.,   0.,  15.,  56.,   1.,   0.,   0.,   0.,   6.,   1.]]), True)
(-10.0, array([[ 16.,   1.,   0.,  15.,  56.,   1.,   3.,   0.,   0.,   7.,   1.]]), True)
(-10.

In [36]:
s.statespace_limits

array([[  0.,   3.],
       [  0.,   3.],
       [  0.,   3.],
       [  0.,   3.],
       [  0.,   3.],
       [  0.,   3.],
       [  0.,   3.],
       [  0.,   3.],
       [  0.,   3.],
       [  0.,  20.],
       [  0.,   1.]])

In [ ]:
print s.possible_actions()
print s.possible_string_actions(s.s0())

In [ ]:
representation = ApproxRep(s, seed = 1)
representation.phi_s(s5[1])

In [ ]:
representation.phi_sa(s5[1], 9)

In [ ]:
s.corpus.values()

In [ ]:
selected_key = s.corpus.keys()[20]
selected_person = s.corpus.get(selected_key)
selected_person

In [ ]:
print s2[1]
Representation.Representation.expand_state_space(s2[1], s.statespace_limits)

In [ ]:
np.cumsum(s.statespace_limits[:-1, 1] - s.statespace_limits[:-1, 0])

In [ ]:
s.statespace_limits

In [14]:
X = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1] ])
y = np.array([-1,1,1,-1])

In [18]:
from sklearn import linear_model
clf = linear_model.SGDRegressor(alpha=0.01, warm_start=True)
clf.fit(X, y)
print clf.coef_

[-0.03215915  0.02858938  0.02960411 -0.02884167]


In [19]:
clf.predict(X)

array([-0.03497334,  0.02577519,  0.02678992, -0.03165585])

## Binary Simulator

In [1]:
from Domains.BinarySimulator20q import BinarySimulator20q
from Experiments.online_fqi import run
import numpy as np
from Representations import Representation

loading model
construct meta info for corpus
[u'birthplace', u'spouse', u'degree', u'gender', u'profession', u'birthday', u'deathplace', u'nationality', u'education', u'Types']
Done initializing
{u'birthplace': [u'Furnes, Norway'], u'education': [u'Norwegian University of Science and Technology'], u'name': u'Mathias Eick', u'degree': [], u'gender': [u'Male'], u'profession': [u'Composer'], u'birthday': [u'979-06-26'], u'deathplace': [], u'nationality': [u'Norway'], u'spouse': [], u'Types': [u'people.person', u'music.artist', u'music.group_member']}
(-1.0, array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
 

TypeError: 'NoneType' object is not iterable

In [2]:
env = BinarySimulator20q()

In [4]:
s = env.s0()
print env.person_inmind
for a_id in range(0, env.actions_num):
    (reward, ns, terminal) = env.step(s, a_id)
    print (reward, ns, terminal)
    s = ns

{u'birthplace': [u'Liverpool'], u'education': [], u'name': u'Cilla Black', u'degree': [], u'gender': [u'Female'], u'profession': [u'Entertainer', u'Singer', u'Actor', u'Media Personality', u'Singer-songwriter', u'Presenter'], u'birthday': [u'943-05-27'], u'deathplace': [], u'nationality': [u'England'], u'spouse': [u'Bobby Willis', u'Cilla Black'], u'Types': [u'award.award_nominee', u'book.author', u'tv.tv_actor', u'film.actor', u'award.award_winner', u'tv.tv_program_guest', u'music.artist', u'music.group_member', u'internet.social_network_user', u'tv.tv_personality', u'people.person', u'film.person_or_entity_appearing_in_film']}
(-1.0, array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  