In [1]:
from Domains.Simulator20q import Simulator20q
import numpy as np

loading model
construct meta info for corpus
Done initializing


In [2]:
s = Simulator20q()

In [3]:
s1 = s.step(s.s0(), 1)
s2 = s.step(s1[1], 2)
s3 = s.step(s2[1], 3)
s4 = s.step(s3[1], 9)
print s1
print s2
print s3
print s4

(-1.0, [None, 'UNKNOWN', None, None, None, None, None, None, None, 1, 0], False)
(-1.0, [None, 'UNKNOWN', u'Male', None, None, None, None, None, None, 2, 0], False)
(-1.0, [None, 'UNKNOWN', u'Male', u'Actor', None, None, None, None, None, 3, 0], False)
(-10.0, [None, 'UNKNOWN', u'Male', u'Actor', None, None, None, None, None, 4, 1], True)


In [4]:
print s.possible_actions()
print s.possible_string_actions(s.s0())

[0 1 2 3 4 5 6 7 8 9]
[u"What is this person's birthplace?", u"What is this person's spouse?", u"What is this person's gender?", u"What is this person's profession?", u"What is this person's birthday?", u"What is this person's deathplace?", u"What is this person's nationality?", u"What is this person's education?", u"What is this person's types?", u'I guess this person is Michael Giacchino']


In [5]:
print s.statespace_limits
print s.field_dim
print s.states_num

[[   0.   62.]
 [   0.   57.]
 [   0.  102.]
 [   0.    2.]
 [   0.    4.]
 [   0.   67.]
 [   0.   71.]
 [   0.   26.]
 [   0.   21.]
 [   0.   20.]
 [   0.    1.]]
{u'birthplace': 60, u'education': 55, u'name': 100, u'degree': 0, u'gender': 2, u'profession': 65, u'birthday': 69, u'deathplace': 24, u'nationality': 19, u'spouse': 103, u'Types': 96}
149800234671360


array([  62.,   57.,  102.,    2.,    4.,   67.,   71.,   26.,   21.,
         20.,    1.])